openapi: 3.0.0
info:
  title: Koderpedia ERP API
  version: 1.0.0
servers:
  - url: 'http://localhost:1323'
    description: Local development server
tags:
  - name: Health Check
    description: Endpoints for checking the health of the API
  - name: Authentication
    description: Endpoints for user authentication and registration
  - name: Crypto
    description: Endpoints for cryptographic operations such as encryption and decryption
paths:
  /api/v1/ping:
    get:
      tags:
        - Health Check
      operationId: GetPing
      summary: Check the health of the API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPingResponse'
  /api/v1/auth/register/phone:
    post:
      tags:
        - Authentication
      operationId: RegisterPhoneNumber
      summary: Register user phone number to app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateNewAccountResponse'
        '400':
          description: Bad request due to invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
  /api/v1/auth/validate/pin:
    post:
      tags:
        - Authentication
      operationId: AuthValidatePin
      summary: Validate a PIN code for authentication.
      description: 'Validate user pin code, if pin already provided login if not, create new pin'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthValidatePinRequest'
      responses:
        '200':
          description: Successful authentication with valid PIN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthValidatePinResponse'
        '400':
          description: 'Bad request, invalid input data.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
        '401':
          description: 'Unauthorized, invalid PIN or authentication failed.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnauthorized'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInternalServerError'
  /api/v1/crypto/encrypt:
    post:
      tags:
        - Crypto
      operationId: CryptoEncryptText
      summary: encrypt plain text to aes encryption
      description: 'Requires Authorization header with the JWT access token returned by AuthValidatePin, formatted as Bearer <token>.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CryptoEncryptTextRequest'
      responses:
        '200':
          description: Result ecnrypted text that already encode to base64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoEncryptTextResponse'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
        '401':
          description: 'Unauthorized, missing or invalid bearer token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnauthorized'
  /api/v1/auth/otp/verify:
    post:
      tags:
        - Authentication
      summary: Verify OTP code for user authentication
      operationId: VerifyNewAuthUserOTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOTPRequest'
      responses:
        '200':
          description: OTP verification successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOTPResponse200'
        '400':
          description: 'Bad request, invalid input data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
        '401':
          description: 'Unauthorized, invalid OTP code'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnauthorized'
        '403':
          description: 'Forbidden, user does not have permission to access this resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorForbidden'
components:
  schemas:
    GetPingResponse:
      type: object
      properties:
        message:
          type: string
          description: The response message for the ping endpoint
          example: PONG
    CreateNewAccountRequest:
      type: object
      required:
        - phoneNo
      properties:
        phoneNo:
          type: string
          description: User phone number
          example: 6281234567890
    CreateNewAccountResponse:
      type: object
      required:
        - id
        - otpCode
      properties:
        id:
          type: string
          description: The unique identifier for the newly created account
          example: 123e4567-e89b-12d3-a456-426
        otpCode:
          type: string
          description: OTP code that could be receive to user
          example: 45142
    VerifyOTPRequest:
      type: object
      required:
        - otp
        - phoneNo
      properties:
        otp:
          type: string
          description: The OTP code sent to the user's phone number for verification
          example: '123456'
        phoneNo:
          type: string
          description: The user's phone number associated with the OTP code
          example: 081234567890
    VerifyOTPResponse200:
      type: object
      required:
        - isValid
        - phoneNo
        - isNewUser
      properties:
        isValid:
          type: boolean
          description: Indicates whether the provided OTP code is valid or not
          example: true
        phoneNo:
          type: string
          description: The user's phone number associated with the OTP code
          example: 081234567890
        note:
          type: string
          description: Additional information or notes regarding the OTP verification result
          example: OTP code is valid and has not expired
        isNewUser:
          type: boolean
          description: Indicates whether the user is new or existing based on the phone number
          example: true
    ErrorBadRequest:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: The error message describing the bad request
          example: Invalid input data
    ErrorUnauthorized:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: The error message describing the unauthorized access
          example: 'Unauthorized, invalid OTP code'
    ErrorForbidden:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: The error message describing the forbidden access
          example: 'Forbidden, you do not have permission to access this resource'
    ErrorInternalServerError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: The error message describing the internal server error.
          example: Internal server error
    CryptoEncryptTextRequest:
      type: object
      required:
        - plainText
      properties:
        plainText:
          type: string
          description: The text that should be encrypted and encoding to base64
          example: VVBLd2JIS0ZJSGlyWlRCWQ==
    CryptoEncryptTextResponse:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          description: encrypted code that already encoded to base64
          example: AzzasSaasdf==
    AuthValidatePinRequest:
      type: object
      required:
        - pin
        - phoneNo
      properties:
        phoneNo:
          type: string
          description: The phone number associated with the PIN code.
          example: 081234567890
        pin:
          type: string
          description: The PIN code to validate for authentication.
          example: '1234'
        retypePin:
          type: string
          description: The retype PIN code to validate for authentication.
          example: '1234'
    AuthValidatePinResponse:
      type: object
      properties:
        userId:
          type: string
          description: Unique identifier for the user.
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        authToken:
          type: string
          description: Authentication token for the user.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
