name: Pull Request Validation

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup GO
        uses: actions/setup-go@v6
        with:
            go-version-file: go.mod
            cache: true

      - name: Install tools
        run: make install-tools

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install swagger-cli
        run: npm install -g swagger-cli
      
      - name: Verify
        run: swagger-cli --version
      
      - name: Initialize app package
        run: make clean init
      
      - name: Run Unit Test
        run: go test -v ./...